In [1]:
import numpy as np
import sympy as sp

In [2]:
#Q3
np.random.seed(58)
A = np.random.randint(0, 10, size=(5, 5))
sp.Matrix(A)
U,S,VT=np.linalg.svd(A)
print('U=',U)
print('S=',S)
print("VT=",VT)


U= [[ 0.5747906  -0.66031112  0.452111    0.16943404  0.02219765]
 [ 0.52329168  0.606935    0.19961628 -0.01639113  0.56363144]
 [ 0.35162139  0.09032599 -0.57077803  0.70853911 -0.20096859]
 [ 0.43124298 -0.1936349  -0.58331495 -0.66049872 -0.00448737]
 [ 0.2935532   0.38725427  0.29950807 -0.18093427 -0.80088598]]
S= [20.22843477  7.05000064  5.65476933  4.58197761  1.06629391]
VT= [[ 0.17736419  0.28623951  0.65228443  0.43640868  0.52027048]
 [ 0.03221644  0.39376529  0.4176116  -0.81547521 -0.0671695 ]
 [ 0.39872359 -0.72092063  0.48194981 -0.06149794 -0.29195091]
 [ 0.06071494  0.44156474  0.17581335  0.37116655 -0.79539885]
 [ 0.89712722  0.21979506 -0.37005355 -0.0547818   0.08313973]]


In [3]:
USVT = np.dot(U, np.dot(np.diag(S), VT))

In [4]:
verification = np.allclose(USVT, A)

if verification:
    print("A equals the product of USVT.")
else:
    print("A does not equal the product of USVT.")

A equals the product of USVT.
